version: 1.0.{build}

os: unstable

environment:
  BOOST_ROOT: C:/Libraries/boost
  GENERATOR: "Visual Studio 12 Win64"
  QT_DIR: C:/Qt/5.4/msvc2013_64_opengl
  BOOST_LIBRARYDIR: C:/Libraries/boost/lib64-msvc-12.0

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - git submodule init
  - git submodule update

build_script:
  - cmake -G "%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DCMAKE_PREFIX_PATH="%QT_DIR%" -H. -Bbuild
  - cmake --build build --config "%CONFIGURATION%"
